[project]
name = "backend"
version = "0.1.0"
requires-python = "==3.9.25"
dependencies = [
    "fastapi>=0.128.8",
    "uvicorn>=0.39.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
